services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/acme.json:/acme.json
      - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"

      # ROUTEUR HTTPS POUR LE DASHBOARD
      - "traefik.http.routers.traefik-dashboard.rule=Host(`famproject.cloud`) && PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth,traefik-strip"

      # BASIC AUTH
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$2y$$05$$NpYg5jk610mgR1X3eGRQvegQcN3fs7GdEmY71sSMiK880cTOehBi6"

      # SUPPRESSION DU PREFIXE
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"

networks:
  traefik-public:
    external: true
